name: interpolated_countdown
description: Flutter package for a countdown widget with interpolated colors.
version: 1.0.0
homepage: https://github.com/aprashantz/interpolated_countdown

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
